[package]
name = "aoc2023"
version = "0.1.0"
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2021"
publish = false

[dependencies]
clap = { version = "4.4.10", features = ["derive", "env"] }
color-eyre = "0.6.2"
reqwest = { version = "0.11.22", features = ["blocking"] }
